spring:
  application:
    name: main
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example
    platform: postgres
  cloud:
    consul:
      host: 121.183.228.40
      port: 8500
    stream:
      bindings:
        commandToController-out-0:
          producer:
            exchange-type: direct
          destination: commandToController
        messageFromController-in-0:
          consumer:
            exchange-type: direct
          destination: reportToMain
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin
logging:
  level:
    com:
      ccwlab:
        main: DEBUG
jwt:
  secret: secret